### ISSUE TITLE
Example doesn't work.

### ISSUE THREAD

**Issue by greenspand** [mulab/rx-realm#3]
Hi . I just tried the sample query but I constantly get alerts from lint. The only thing I've done was to replace Foo with my own POJO. Please help. Your library realy looks promising.
Thx.

**Comment by cgcgbcbc** [comment]
Hi, does your POJO extends `RealmObject` ?

**Comment by greenspand** [comment]
Hi no. I didn't know I should extend. I thoght it would be wrapped. Thx for the tip. Could you please update the readme so that users now that they should extend RealmObject. Reason is, I didn't use realm before but I started using your library. Thx.

**Comment by cgcgbcbc** [comment]
Thanks for your advice, I'll make it more clearly.
