### ISSUE TITLE
Please update realm.io library version.

### ISSUE THREAD

**Issue by greenspand** [mulab/rx-realm#5]
When compilig I get an error/ notification that there is already a newer realm.io library version

**Comment by cgcgbcbc** [comment]
@greenspand I've added a new tag `1.1.0` which is compatible with realm 0.85.1.
Note that upgrade from realm 0.82.2 to 0.83  changed database format.

**Comment by greenspand** [comment]
Hi Guang,

Awesome. Thx for the help. No worries. I just started with realm and will
play in the weekend some more. I don't have a production critical database.
Thx for the info though.
