### ISSUE TITLE
Cant install, conflict with com.neenbedankt.gradle.plugins:android-apt:1.8

### ISSUE THREAD

**Issue by Zeyad-37** [mulab/rx-realm#9]
Gradle 'Test' project refresh failed
Error:Could not find com.neenbedankt.gradle.plugins:android-apt:1.8.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/neenbedankt/gradle/plugins/android-apt/1.8/android-apt-1.8.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/neenbedankt/gradle/plugins/android-apt/1.8/android-apt-1.8.jar
    https://jitpack.io/com/neenbedankt/gradle/plugins/android-apt/1.8/android-apt-1.8.pom
    https://jitpack.io/com/neenbedankt/gradle/plugins/android-apt/1.8/android-apt-1.8.jar
Required by:
    Test:app:unspecified

**Comment by cgcgbcbc** [comment]
Did you have jcenter() in your repositories?

**Comment by Zeyad-37** [comment]
I dont think so. 
This is my build.gradle file:

buildscript {
    repositories {
         maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    applicationId "com.zeyad.picnictest"
    minSdkVersion 16
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled true
        shrinkResources true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    // Google Play Services
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    // Support
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:palette-v7:23.1.1'
    // Network
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.7.0'
//    compile 'com.squareup.okhttp3:okhttp:3.0.1'
//    compile 'com.squareup.retrofit:converter-protobuf:1.9.0'
//    compile 'com.squareup.retrofit:converter-wire:1.9.0'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    // Rx
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'
    //DB
    compile 'io.realm:realm-android:0.87.2'
    compile 'com.github.mulab:rx-realm:1.1.0'
    // Injection
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'javax.annotation:jsr250-api:1.0'
    compile 'com.google.dagger:dagger:2.0'
    apt 'com.google.dagger:dagger-compiler:2.0'
    // Leak Canary
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'
}

**Comment by cgcgbcbc** [comment]
Can you change your repo config to something like

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

Since android-apt is required by `realm-java`, and it's only available in jcenter, not on jitpack

**Comment by Zeyad-37** [comment]
It works now thanks :)
